version: 2
phases:
   build: 
     commands:
         - echo enter the build phase
         - mvn clean package
   post_build:
     commands:
       - echo build completed successfully
artifacts:
   files:
     - target/smartcity.jar
   discard-paths: yes